[package]
name = "south-upper-sensor"
version = "0.1.0"
edition = "2024"

[dependencies]
embassy-stm32 = { version = "0.6.0", features = [ "defmt", "time", "time-driver-any", "stm32h723vg", "memory-x", "unstable-pac", "exti"]  }
embassy-sync = { version = "0.8.0", features = ["defmt"] }
embassy-executor = { version = "0.10.0", features = ["platform-cortex-m", "executor-thread", "defmt"] }
embassy-time = { version = "0.5.1", features = ["defmt", "defmt-timestamp-uptime", "tick-hz-1_000_000"] }
embassy-futures = { version = "0.1.2" }

defmt = "1.0"
defmt-rtt = "1.1"

cortex-m = { version = "0.7.7", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = "0.7.5"
panic-probe = { version = "1.0", features = ["print-defmt"] }
heapless = { version = "0.9", default-features = false }

embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
embedded-io-async = { version = "0.7.0" }
embedded-can = "0.4.1"
static_cell = { version = "2.1.1", features = ["nightly"] }

south-common = { features = ["h7"], git = "https://git@github.com/S2outh/south-common.git" }

lsm6dsv32 = { git = "https://github.com/S2outh/imu-driver.git", features = ["debug"] }
rm3100 = { git = "https://github.com/S2outh/magneto-driver.git" }
hscmrnn030pa = { git = "https://github.com/S2outh/baro-driver.git" }

phoenix = { git = "ssh://git@github.com/S2outh/phoenix-vibing.git", branch = "dev" }

portable-atomic = "1.13.1"

[profile.release]
debug = 2
